name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm build
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "Host app.gurupass.tech" >> ~/.ssh/config
          echo "  HostName app.gurupass.tech" >> ~/.ssh/config
          echo "  User ubuntu" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        
      - name: Deploy
        run: |
          rsync -avz --delete dist/ ubuntu@app.gurupass.tech:~/guru-vpn-tma/dist/
          ssh ubuntu@app.gurupass.tech 'cd ~/guru-vpn-tma && pm2 restart guru-vpn-tma || pm2 start npm --name guru-vpn-tma -- run preview'
